// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: grpc/proto/status_service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Rs) Reset() {
	*x = Rs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_status_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rs) ProtoMessage() {}

func (x *Rs) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_status_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rs.ProtoReflect.Descriptor instead.
func (*Rs) Descriptor() ([]byte, []int) {
	return file_grpc_proto_status_service_proto_rawDescGZIP(), []int{0}
}

func (x *Rs) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Rq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Rq) Reset() {
	*x = Rq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_status_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rq) ProtoMessage() {}

func (x *Rq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_status_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rq.ProtoReflect.Descriptor instead.
func (*Rq) Descriptor() ([]byte, []int) {
	return file_grpc_proto_status_service_proto_rawDescGZIP(), []int{1}
}

func (x *Rq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_proto_status_service_proto protoreflect.FileDescriptor

var file_grpc_proto_status_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1c, 0x0a, 0x02, 0x52, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x1e, 0x0a, 0x02, 0x52, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x26, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x15, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x03, 0x2e,
	0x52, 0x73, 0x1a, 0x03, 0x2e, 0x52, 0x71, 0x42, 0x0a, 0x5a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_status_service_proto_rawDescOnce sync.Once
	file_grpc_proto_status_service_proto_rawDescData = file_grpc_proto_status_service_proto_rawDesc
)

func file_grpc_proto_status_service_proto_rawDescGZIP() []byte {
	file_grpc_proto_status_service_proto_rawDescOnce.Do(func() {
		file_grpc_proto_status_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_status_service_proto_rawDescData)
	})
	return file_grpc_proto_status_service_proto_rawDescData
}

var file_grpc_proto_status_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_status_service_proto_goTypes = []interface{}{
	(*Rs)(nil), // 0: Rs
	(*Rq)(nil), // 1: Rq
}
var file_grpc_proto_status_service_proto_depIdxs = []int32{
	0, // 0: StatusService.Heartbeat:input_type -> Rs
	1, // 1: StatusService.Heartbeat:output_type -> Rq
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_status_service_proto_init() }
func file_grpc_proto_status_service_proto_init() {
	if File_grpc_proto_status_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_status_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_status_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_status_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_status_service_proto_goTypes,
		DependencyIndexes: file_grpc_proto_status_service_proto_depIdxs,
		MessageInfos:      file_grpc_proto_status_service_proto_msgTypes,
	}.Build()
	File_grpc_proto_status_service_proto = out.File
	file_grpc_proto_status_service_proto_rawDesc = nil
	file_grpc_proto_status_service_proto_goTypes = nil
	file_grpc_proto_status_service_proto_depIdxs = nil
}
